### ISSUE TITLE
Could you provide a download link for the virtual machine environment?

### ISSUE THREAD

**Issue by wahoyi** [irshimul/dns-cache-poisoning-attack-reloaded#1]
I am a new network security, would like to repeat your attack, but I am very unfamiliar with the environment configuration of this attack, if possible, could you please provide a download link to your virtual machine?

**Comment by imranur-rahman** [comment]
I built those VM's from scratch, and I haven't uploaded those. I think you can configure your isolated networking environment with those software and operating systems. But if you need, I can write something describing the environment setup for everyone to try this out. Apart from that, I will try to upload those VM's, but it will take some time.

**Comment by wahoyi** [comment]
Thank you for your reply. I would really appreciate it if you could give me some description of what you said. I did have some difficulties in configuring Free-BSD. And this is my email：wahoyicn@gmail.com

**Comment by imranur-rahman** [comment]
Communicated over email.

**Comment by VaTanJo** [comment]
Hello, can I also ask for some description files? I've tried to setup VMs, but it's not going well
My email is kakerasora@gmail.com , thanks
